# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Radius-Client
version:      0.01
version_from: Client.pm
installdirs:  site
requires:
    Net::Radius::Dictionary:       1.55
    Net::Radius::Packet:           1.55

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
